### PR TITLE
use node crypto API

### PR DESCRIPTION
**Pull request by mreinstein**
Math.random() is notoriously bad at generating pseudo-random values. the node API provides a better source.

### CODE REVIEW

**Comment by mreinstein** [comment]
@matthewmueller would you be open to pushing a new version of this to npm?

**Comment by mreinstein** [comment]
@matthewmueller any thoughts on this?

**Comment by matthewmueller** [comment]
sorry @mreinstein for the late response, I think this is better suited for another library. Definitely aware of the shortcomings of Math.random, I'd like to just keep this version super tiny and dependency free.

If I need a strong uid generator, I use: https://github.com/coreh/uid2 which looks to be about the same thing.

**Comment by matthewmueller** [comment]
I've added a note to the readme to direct people to use `uid2` if they need a stronger random number generator

**Pull request closed without merging**
